name: GitHub Pages Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Create NPM Setting
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          @zoi-dayo:registry=https://npm.pkg.github.com
          always-auth=true" > .npmrc

      - name: Install packages
        run: npm ci

      - name: Build
        run: npx @zoi-dayo/scml build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist